I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/nana.rpy", line 146, in script
    K "(Nah, no way. I’m too uncoordinated.)"
Exception: Sayer 'K' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/nana.rpy", line 146, in script
    K "(Nah, no way. I’m too uncoordinated.)"
  File "/home/cero/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/home/cero/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'K' is not defined.

Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid
Ren'Py 7.3.5.606
WTHC 1.0
Wed Jul  1 11:16:06 2020
